language: cpp

compiler: clang

install:
  - wget https://github.com/dut-lang/dut/archive/master.tar.gz
  - tar -xzvf master.tar.gz
  - cd dut-master && make

script:
  - ls -l
  - ls ./dut-master/src/dut
  - ./dut-master/src/dut/dut unittest.dut
