language: cpp

compiler: clang

install:
  - wget https://github.com/dut-lang/dut/archive/master.tar.gz
  - tar -xzvf dut-master.tar.gz
  - cd dut-master && make

script: ./dut-master/src/dut/dut unittest.dut
